language: c
install:
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.7/libsodium-1.0.7.tar.gz
  - tar -xzvf libsodium-1.0.7.tar.gz
  - cd libsodium-1.0.7 && ./configure --prefix=/usr && make && sudo make install
  - cd ~/
script: mkdir travis-build && cd travis-build && cmake -DCMAKE_INSTALL_PREFIX=/usr ../ && make
